CREATE TABLE "authentications" (
  "id" uuid PRIMARY KEY NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "phone" varchar,
  "username" varchar,
  "password_hash" varchar NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz,
  "is_suspended" boolean DEFAULT false,
  "is_deleted" boolean DEFAULT false,
  "is_verified" boolean DEFAULT false,
  "is_email_verified" boolean DEFAULT false,
  "deleted_at" timestamptz,
  "verified_at" timestamptz,
  "suspended_at" timestamptz,
  "login_attempts" int DEFAULT 0,
  "password_last_changed" timestamptz,
  "lockout_duration" int DEFAULT 60,
  "lockout_until" timestamptz,
  "is_mfa_enabled" boolean DEFAULT false,
  "is_oauth_user" boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS users (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL UNIQUE,
  "first_name" varchar,
  "last_name" varchar,
  "image_url" VARCHAR,
  FOREIGN KEY (user_id) REFERENCES authentications(id)
);

CREATE TABLE IF NOT EXISTS "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS "user_roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "role_id" int NOT NULL
);

CREATE INDEX ON "authentications" (
        "email",
        "phone",
        "username",
        "created_at",
        "updated_at"
    );

CREATE INDEX ON "user_roles" ("role_id", "user_id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
