CREATE TABLE "user_logins" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "login_at" timestamptz DEFAULT (now()),
  "ip_address" inet,
  "user_agent" varchar
);

CREATE TABLE "sessions" (
  "id" uuid PRIMARY KEY NOT NULL,
  "user_id" uuid NOT NULL,
  -- "access_token" VARCHAR UNIQUE NOT NULL,
  "refresh_token" varchar UNIQUE NOT NULL,
  -- "access_token_exp" timestamptz NOT NULL,
  "refresh_token_exp" timestamptz NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz,
  "invalidated_at" timestamptz,
  "last_active_at" timestamptz,
  "blocked_at" timestamptz,
  "user_agent" text NOT NULL,
  "ip_address" inet NOT NULL,
  "fcm_token" VARCHAR
);

CREATE TABLE "email_verification_requests" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "email" varchar NOT NULL,
  "token" varchar NOT NULL UNIQUE,
  "is_verified" boolean DEFAULT false,
  "created_at" timestamptz DEFAULT (now()),
  "expires_at" timestamptz NOT NULL
);


CREATE INDEX ON "user_logins" ("user_id", "login_at");
CREATE INDEX ON "sessions" ("user_id", "refresh_token_exp", "refresh_token");

CREATE INDEX ON "email_verification_requests" ("user_id", "token", "email", "expires_at");


ALTER TABLE "user_logins" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");

ALTER TABLE "email_verification_requests" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");