CREATE TABLE "password_reset_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "email" varchar NOT NULL,
  "token" varchar NOT NULL UNIQUE,
  "used" boolean DEFAULT false,
  "created_at" timestamptz DEFAULT (now()),
  "expires_at" timestamptz NOT NULL
);

CREATE TABLE "two_factor_secrets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL, -- UNIQUE,
  "secret_key" varchar NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "two_factor_revocation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "revoked_at" timestamptz,
  "revocation_reason" varchar
  -- "revoked_by" UUID REFERENCES users(id)
);

CREATE TABLE "two_factor_backup_codes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "code" varchar NOT NULL,
  "used" boolean DEFAULT false
);

CREATE TABLE "account_recovery_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "email" varchar NOT NULL,
  "used" BOOLEAN DEFAULT false,
  "recovery_token" varchar unique not null,
  "requested_at" timestamptz DEFAULT (now()),
  "expires_at" timestamptz not null,
  "completed_at" timestamptz
);

CREATE INDEX ON "password_reset_requests" ( "user_id","email", "token", "expires_at");

CREATE INDEX ON "account_recovery_requests" ( "user_id", "recovery_token");


ALTER TABLE "password_reset_requests" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");

ALTER TABLE "two_factor_secrets" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");

ALTER TABLE "two_factor_revocation" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");

ALTER TABLE "two_factor_backup_codes" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");

ALTER TABLE "account_recovery_requests" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");
