// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Authentication struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               string             `json:"email"`
	Phone               pgtype.Text        `json:"phone"`
	Username            pgtype.Text        `json:"username"`
	PasswordHash        string             `json:"password_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	IsSuspended         pgtype.Bool        `json:"is_suspended"`
	IsDeleted           pgtype.Bool        `json:"is_deleted"`
	IsVerified          pgtype.Bool        `json:"is_verified"`
	IsEmailVerified     pgtype.Bool        `json:"is_email_verified"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	VerifiedAt          pgtype.Timestamptz `json:"verified_at"`
	SuspendedAt         pgtype.Timestamptz `json:"suspended_at"`
	LoginAttempts       pgtype.Int4        `json:"login_attempts"`
	PasswordLastChanged pgtype.Timestamptz `json:"password_last_changed"`
	LockoutDuration     pgtype.Int4        `json:"lockout_duration"`
	LockoutUntil        pgtype.Timestamptz `json:"lockout_until"`
	IsMfaEnabled        pgtype.Bool        `json:"is_mfa_enabled"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID        int32       `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	ImageUrl  pgtype.Text `json:"image_url"`
}

type UserRole struct {
	ID     int32       `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	RoleID int32       `json:"role_id"`
}
